// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package com.grpc.dto;

public interface DemoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:helloworld.DemoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <dto>int32 dto = 1;</dto>
   */
  int getCode();

  /**
   * <dto>string msg = 2;</dto>
   */
  String getMsg();
  /**
   * <dto>string msg = 2;</dto>
   */
  com.google.protobuf.ByteString
      getMsgBytes();

  /**
   * <dto>string data = 3;</dto>
   */
  String getData();
  /**
   * <dto>string data = 3;</dto>
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
